coverage_service: html
xcodeproj: workshopBitriseIOS.xcodeproj
workspace: workshopBitriseIOS.xcworkspace
scheme: workshopBitriseIOS
output_directory: build/slather-report
ignore:
  - Pods/*
  - "Frameworks/*"
