# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "CI"
  lane :ci do
    # pod
    cocoapods(
      clean: true
    )

    # test
    run_tests(
      workspace: "workshopBitriseIOS.xcworkspace",
      devices: ["iPhone 6s"],
      scheme: "workshopBitriseIOS"
    )

    # lint
    swiftlint(
      executable: "Pods/SwiftLint/swiftlint",
      output_file: "build/swiftlint_result.json",
      ignore_exit_status: true
    )

    # slather
    slather(
      use_bundle_exec: "true",
    )
  end

  desc "CD"
  lane :cd do
    # pod
    cocoapods(
      clean: true
    )

    # set certificates & provisioning profile
    match(
      type: "appstore",
      readonly: true,
      output_path: "match/"
    )
    disable_automatic_code_signing
    update_project_provisioning(
      xcodeproj: "workshopBitriseIOS.xcodeproj",
      target_filter: "workshopBitriseIOS",
      profile: "./match/" + ENV["APP_PROVISIONING_PROFILE_IDENTIFIER"] + ".mobileprovision"
    )


    # increment build number
    increment_build_number(
      build_number: 1,
      xcodeproj: "workshopBitriseIOS.xcodeproj"
    )

    # build for release

    gym(
      scheme: "workshopBitriseIOS",
      include_bitcode: true,
      skip_profile_detection: true,
      clean: true,
      codesigning_identity: ENV["APPSTORE_SIGNING_IDENTITY"],
      verbose: true
    )
  end
end
