# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "CI"
  lane :ci do
    # pod
    cocoapods(
      clean: true
    )

    # test
    run_tests(
      workspace: "workshopBitriseIOS.xcworkspace",
      devices: ["iPhone 6s"],
      scheme: "workshopBitriseIOS"
    )

    # lint
    swiftlint(
      executable: "Pods/SwiftLint/swiftlint",
      output_file: "build/swiftlint_result.json",
      ignore_exit_status: true
    )

    end
end
